apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: shop-app
type: Opaque
stringData:
  # Database
  DATABASE_URL: 'mysql+pymysql://dat515user:admin123@mysql:3306/DAT515'
  ANALYTICS_DATABASE_URL: 'mysql+pymysql://analytics_user:analytics_pass@analyticsdb:3306/analytics_db'
  REDIS_URL: 'redis://redis:6379/0'
  
  # URLs
  FRONTEND_URL: 'http://34.88.175.32'
  CORS_ORIGINS: 'http://34.88.175.32,http://localhost:3000,http://localhost:5173'
  
  # AWS S3 (for product images)
  AWS_ACCESS_KEY_ID: 'your-aws-access-key'
  AWS_SECRET_ACCESS_KEY: 'your-aws-secret-key'
  AWS_REGION: 'eu-north-1'
  S3_BUCKET_NAME: 'your-bucket-name'
  
  # Stripe (for payments)
  STRIPE_SECRET_KEY: 'sk_test_...'
  STRIPE_PUBLISHABLE_KEY: 'pk_test_...'
  #STRIPE_WEBHOOK_SECRET: 'whsec_...'