global:
  scrape_interval: 5s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # FastAPI backend metrics
  - job_name: 'fastapi-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']

  # cAdvisor container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
